In [81]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [82]:
from sklearn import datasets

In [83]:
data=pd.read_csv('C:/Users/DELL/Downloads/diabetes.csv')
data

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [84]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype  
---  ------                    --------------  -----  
 0   Pregnancies               768 non-null    int64  
 1   Glucose                   768 non-null    int64  
 2   BloodPressure             768 non-null    int64  
 3   SkinThickness             768 non-null    int64  
 4   Insulin                   768 non-null    int64  
 5   BMI                       768 non-null    float64
 6   DiabetesPedigreeFunction  768 non-null    float64
 7   Age                       768 non-null    int64  
 8   Outcome                   768 non-null    int64  
dtypes: float64(2), int64(7)
memory usage: 54.1 KB


In [85]:
df=data.astype('int64')
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0              6      148             72             35        0   33   
1              1       85             66             29        0   26   
2              8      183             64              0        0   23   
3              1       89             66             23       94   28   
4              0      137             40             35      168   43   
..           ...      ...            ...            ...      ...  ...   
763           10      101             76             48      180   32   
764            2      122             70             27        0   36   
765            5      121             72             23      112   26   
766            1      126             60              0        0   30   
767            1       93             70             31        0   30   

     DiabetesPedigreeFunction  Age  Outcome  
0                           0   50        1  
1                           0   31        0  
2                           0   32        1  
3                           0   21        0  
4                           2   33        1  
..                        ...  ...      ...  
763                         0   63        0  
764                         0   27        0  
765                         0   30        0  
766                         0   47        1  
767                         0   23        0  

[768 rows x 9 columns]

In [86]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 768 entries, 0 to 767
Data columns (total 9 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Pregnancies               768 non-null    int64
 1   Glucose                   768 non-null    int64
 2   BloodPressure             768 non-null    int64
 3   SkinThickness             768 non-null    int64
 4   Insulin                   768 non-null    int64
 5   BMI                       768 non-null    int64
 6   DiabetesPedigreeFunction  768 non-null    int64
 7   Age                       768 non-null    int64
 8   Outcome                   768 non-null    int64
dtypes: int64(9)
memory usage: 54.1 KB


In [87]:
df.head(10)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  \
0            6      148             72             35        0   33   
1            1       85             66             29        0   26   
2            8      183             64              0        0   23   
3            1       89             66             23       94   28   
4            0      137             40             35      168   43   
5            5      116             74              0        0   25   
6            3       78             50             32       88   31   
7           10      115              0              0        0   35   
8            2      197             70             45      543   30   
9            8      125             96              0        0    0   

   DiabetesPedigreeFunction  Age  Outcome  
0                         0   50        1  
1                         0   31        0  
2                         0   32        1  
3                         0   21        0  
4                         2   33        1  
5                         0   30        0  
6                         0   26        1  
7                         0   29        0  
8                         0   53        1  
9                         0   54        1

In [88]:
df.isnull().sum()

Pregnancies                 0
Glucose                     0
BloodPressure               0
SkinThickness               0
Insulin                     0
BMI                         0
DiabetesPedigreeFunction    0
Age                         0
Outcome                     0
dtype: int64

In [89]:
df.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.548177                  0.071615   33.240885    0.348958  
std      7.860602                  0.277494   11.760232    0.476951  
min      0.000000                  0.000000   21.000000    0.000000  
25%     27.000000                  0.000000   24.000000    0.000000  
50%     32.000000                  0.000000   29.000000    0.000000  
75%     36.000000                  0.000000   41.000000    1.000000  
max     67.000000                  2.000000   81.000000    1.000000

In [90]:
import pandas as pd

In [91]:
df.drop(['DiabetesPedigreeFunction'],inplace=True,axis=1)


In [92]:
df


Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  Age  \
0              6      148             72             35        0   33   50   
1              1       85             66             29        0   26   31   
2              8      183             64              0        0   23   32   
3              1       89             66             23       94   28   21   
4              0      137             40             35      168   43   33   
..           ...      ...            ...            ...      ...  ...  ...   
763           10      101             76             48      180   32   63   
764            2      122             70             27        0   36   27   
765            5      121             72             23      112   26   30   
766            1      126             60              0        0   30   47   
767            1       93             70             31        0   30   23   

     Outcome  
0          1  
1          0  
2          1  
3          0  
4          1  
..       ...  
763        0  
764        0  
765        0  
766        1  
767        0  

[768 rows x 8 columns]

In [93]:
df['Outcome']

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [94]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  Age  \
0              6      148             72             35        0   33   50   
1              1       85             66             29        0   26   31   
2              8      183             64              0        0   23   32   
3              1       89             66             23       94   28   21   
4              0      137             40             35      168   43   33   
..           ...      ...            ...            ...      ...  ...  ...   
763           10      101             76             48      180   32   63   
764            2      122             70             27        0   36   27   
765            5      121             72             23      112   26   30   
766            1      126             60              0        0   30   47   
767            1       93             70             31        0   30   23   

     Outcome  
0          1  
1          0  
2          1  
3          0  
4          1  
..       ...  
763        0  
764        0  
765        0  
766        1  
767        0  

[768 rows x 8 columns]

In [95]:
df['Outcome']=df['Outcome'].map({0:'false',1:'true'})

In [96]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  Age  \
0              6      148             72             35        0   33   50   
1              1       85             66             29        0   26   31   
2              8      183             64              0        0   23   32   
3              1       89             66             23       94   28   21   
4              0      137             40             35      168   43   33   
..           ...      ...            ...            ...      ...  ...  ...   
763           10      101             76             48      180   32   63   
764            2      122             70             27        0   36   27   
765            5      121             72             23      112   26   30   
766            1      126             60              0        0   30   47   
767            1       93             70             31        0   30   23   

    Outcome  
0      true  
1     false  
2      true  
3     false  
4      true  
..      ...  
763   false  
764   false  
765   false  
766    true  
767   false  

[768 rows x 8 columns]

In [97]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  Age  \
0              6      148             72             35        0   33   50   
1              1       85             66             29        0   26   31   
2              8      183             64              0        0   23   32   
3              1       89             66             23       94   28   21   
4              0      137             40             35      168   43   33   
..           ...      ...            ...            ...      ...  ...  ...   
763           10      101             76             48      180   32   63   
764            2      122             70             27        0   36   27   
765            5      121             72             23      112   26   30   
766            1      126             60              0        0   30   47   
767            1       93             70             31        0   30   23   

    Outcome  
0      true  
1     false  
2      true  
3     false  
4      true  
..      ...  
763   false  
764   false  
765   false  
766    true  
767   false  

[768 rows x 8 columns]

In [99]:
x=df.drop('Outcome',axis=1)
x

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin  BMI  Age
0              6      148             72             35        0   33   50
1              1       85             66             29        0   26   31
2              8      183             64              0        0   23   32
3              1       89             66             23       94   28   21
4              0      137             40             35      168   43   33
..           ...      ...            ...            ...      ...  ...  ...
763           10      101             76             48      180   32   63
764            2      122             70             27        0   36   27
765            5      121             72             23      112   26   30
766            1      126             60              0        0   30   47
767            1       93             70             31        0   30   23

[768 rows x 7 columns]

In [125]:
y=df['Outcome']
y=y.map({'true':1,'false':0})

In [126]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

In [128]:
from sklearn.model_selection import train_test_split

In [129]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=10)

In [130]:
from sklearn.neighbors import KNeighborsClassifier

In [131]:
obj2=KNeighborsClassifier()

In [132]:
obj2.fit(x_train,y_train)

KNeighborsClassifier()

In [133]:
y_train

378    1
609    0
719    1
441    0
425    1
      ..
369    1
320    0
527    0
125    1
265    0
Name: Outcome, Length: 691, dtype: int64

In [134]:
train_predict=obj2.predict(x_train)
train_predict

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,

In [135]:
y_test

568    0
620    0
456    0
197    1
714    0
      ..
582    0
230    1
721    0
559    0
192    1
Name: Outcome, Length: 77, dtype: int64

In [136]:
test_predict=obj2.predict(x_test)
test_predict

array([1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1], dtype=int64)

In [137]:
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score,f1_score

In [138]:
confusion_matrix(y_train,train_predict)

array([[397,  52],
       [ 79, 163]], dtype=int64)

In [139]:
accuracy_score(y_train,train_predict)

0.8104196816208393

In [140]:
confusion_matrix(y_test,test_predict)

array([[39, 12],
       [15, 11]], dtype=int64)

In [144]:
(39+11)/(39+12+15+11)

0.6493506493506493

In [141]:
accuracy_score(y_test,test_predict)

0.6493506493506493

In [147]:
(39)/(39+12)

0.7647058823529411

In [143]:
precision_score(y_test,test_predict)

0.4782608695652174

In [150]:
(39)/(39+11)

0.78

In [148]:
recall_score(y_test,test_predict)

0.4230769230769231

In [151]:
f1_score(y_test,test_predict)

0.44897959183673475